## TODO 
# - Update connection when update datasource

### create connection
POST {{HOST_DEV}}/connections
content-type: application/json
authorization: {{TOKEN}}

{ 
  "stationId": "626917f6afef13001dee67b8",
  "items": [
    {"deviceKey": "H2S", "systemKey": "H2S", "ratio": 1, "status": "enabled", "datasourceId": "81ff1020-2067-4fe3-9635-6811fcc43c29"},
    {"deviceKey": "TSS", "systemKey": null, "ratio": 1, "status": "enabled", "datasourceId": "81ff1020-2067-4fe3-9635-6811fcc43c29"},
    {"deviceKey": "pH", "systemKey": "pH", "ratio": 1, "status": "enabled", "datasourceId": "81ff1020-2067-4fe3-9635-6811fcc43c29"}
  ]
}

### fake push data
POST {{HOST_DEV}}/push-data
content-type: application/json
authorization: {{TOKEN}}

{
  "datasourceKey": "DL02_AE3743",
  "receivedAt": "2022-08-31T17:00:00.000",
  "measuringLogs": {
    "COD": {"value": 10, "statusDevice": "00"},
    "TSS": {"value": 10, "statusDevice": "01"},
    "pH": {"value": 10, "statusDevice": "01"},
    "Dust": {"value": 10, "statusDevice": "02"},
    "H2S": {"value": 10, "statusDevice": "02"},
    "Flow": {"value": 10, "statusDevice": "02"},
    "Amoni": {"value": 10, "statusDevice": "02"},
    "Total": {"value": 10, "statusDevice": "02"},
    "Amoniac": {"value": 10, "statusDevice": "02"},
    "Temp": {"value": 10, "statusDevice": "02"},
    "Temp": {"value": 11, "statusDevice": "02"}
  }
}

### create datasources
POST {{HOST_DEV}}/datasources
content-type: application/json
authorization: {{TOKEN}}

{
    "datasourceKey": "DL01_AE3745",
    "devices": ["Dust", "COD", "TSS"]
}

### update device for datasources
POST {{HOST_DEV}}/datasources/add-devices
content-type: application/json
authorization: {{TOKEN}}

{
    "datasourceKey": "DL01_AE3745",
    "devices": ["TSS", "COD", "TSS"]
}
