### create connection
POST {{HOST_DEV}}/connections
content-type: application/json
authorization: {{TOKEN}}

{
    "stationId": "60112a674be0bf001cebe760",
    "datasourceIds": ["9f945e8b-cae0-4313-831e-d1134ad5a574", "81347bce-b46f-4432-aae8-f38b0a787bf7"],
    "items": [
      {"deviceKey": "COD", "systemKey": "COD", "ratio": 1, "status": "enabled", "datasourceId": "81347bce-b46f-4432-aae8-f38b0a787bf7"},
      {"deviceKey": "TSS", "systemKey": null, "ratio": 2, "status": "enabled", "datasourceId": "81347bce-b46f-4432-aae8-f38b0a787bf7"},
      {"deviceKey": "pH", "systemKey": "pH", "ratio": 2, "status": "enabled", "datasourceId": "81347bce-b46f-4432-aae8-f38b0a787bf7"},
      {"deviceKey": "Temp", "systemKey": null, "ratio": 2, "status": "enabled", "datasourceId": "81347bce-b46f-4432-aae8-f38b0a787bf7"}
    ]
}

### fake push data
POST {{HOST_DEV}}/push-data
content-type: application/json
authorization: {{TOKEN}}

{
  "datasourceKey": "DL01_AE3743",
  "receivedAt": "2022-08-31T17:00:00.000",
  "measuringLogs": {
    "COD": {"value": 12.43, "statusDevice": "01"},
    "pH": {"value": 12.43, "statusDevice": "01"},
    "TSS": {"value": 12.43, "statusDevice": "01"},
    "Temp": {"value": 12.43, "statusDevice": "02"}
  } 
}

### create datasources
POST {{HOST_DEV}}/datasources
content-type: application/json
authorization: {{TOKEN}}

{
    "datasourceKey": "DL01_AE3745",
    "devices": ["Dust", "COD", "TSS"]
}

### update device for datasources
POST {{HOST_DEV}}/datasources/add-devices
content-type: application/json
authorization: {{TOKEN}}

{
    "datasourceKey": "DL01_AE3745",
    "devices": ["TSS", "COD", "TSS"]
}
