### create connection
POST {{HOST_DEV}}/connections
content-type: application/json
authorization: {{TOKEN}}

{
    "stationId": "60112a674be0bf001cebe760",
    "items": [
      {"deviceKey": "TSS", "systemKey": "TSS", "ratio": 1, "status": "enabled", "datasourceId": "2e221068-4448-4cb8-b28e-1a497de9061f"},
      {"deviceKey": "COD", "systemKey": "TSS", "ratio": 1, "status": "enabled", "datasourceId": "2e221068-4448-4cb8-b28e-1a497de9061f"},
      {"deviceKey": "Dust", "systemKey": "TSS", "ratio": 1, "status": "enabled", "datasourceId": "91ec9dbb-7420-4ea0-a370-91dab5c948cd"}
    ]
}

### fake push data
POST {{HOST_DEV}}/push-data
content-type: application/json
authorization: {{TOKEN}}

{
  "stationId": "DL01_AE3745",
  "receivedAt": "2022-08-31T17:00:00.000",
  "measures": [
    {
      "parameter": "Dust",
      "statusDevice": 2,
      "value": 10
    },
    {
      "parameter": "pH",
      "statusDevice": 2,
      "value": 10
    },
    {
      "parameter": "COD",
      "statusDevice": 2,
      "value": 10
    }
  ]
}

### create datasources
POST {{HOST_DEV}}/datasources
content-type: application/json
authorization: {{TOKEN}}

{
    "datasourceKey": "DL 01",
    "devices": ["Dust", "COD", "TSS"]
}

### update device for datasources
POST {{HOST_DEV}}/datasources/add-devices
content-type: application/json
authorization: {{TOKEN}}

{
    "datasourceKey": "DL 01",
    "devices": ["TSS", "COD", "TSS"]
}
