{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  {{- if .Values.annotations }}
  annotations:
  {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "common.names.fullname" . }}
    helm.sh/chart: {{ include "common.names.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount | default .Values.global.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "common.names.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "common.names.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Never"}}
          {{- if .Values.command }}
          command: {{ .Values.command }}
          {{- end }}
          {{- if .Values.args }}
          args: {{ .Values.args }}
          {{- end }}
          ports:
            {{- range .Values.services -}}
            {{- range $port:= .specs}}
            - name: {{ .name }}
              containerPort: {{ .targetPort | default .port}}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
            {{- end }}
          {{- if (merge .Values.global.environment (.Values.environment | default )) }}
          env:
          {{- range $name, $value := merge .Values.global.environment .Values.environment}}
          - name: {{ $name | quote}}
            value: {{ $value | quote }}
          {{- end }}
          {{- range $name, $value := merge .Values.global.environmentRef .Values.environmentRef}}
          - name: {{ $name | quote}}
            valueFrom:
              fieldRef:
                fieldPath: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.volumes }}
          {{- if .Values.volumes.enabled }}
          volumeMounts:
            {{- range $conf := .Values.volumes.configMaps }}
            - mountPath: {{ $conf.mountPath }}
              name: {{ $conf.name }}-volume
            {{- end }}
            {{- if .Values.volumes.pvc.enabled }}
            - mountPath: {{ .Values.volumes.pvc.mountPath }}
              name: {{ .Values.volumes.pvc.existing_claim | default .Values.volumes.pvc.name }}-volume
            {{- end }}
          {{- end }}
          {{- end }}
      {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- end}}
      {{- if .Values.volumes }}
      {{- if .Values.volumes.enabled }}
      volumes:
        {{- range $conf := .Values.volumes.configMaps }}
        - name: {{ $conf.name }}-volume
          configMap:
            name: {{ $conf.name }}
      {{- end }}
      {{- if .Values.volumes.pvc.enabled}}
        - name: {{ .Values.volumes.pvc.existing_claim | default .Values.volumes.pvc.name }}-volume
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.pvc.existing_claim | default .Values.volumes.pvc.name }}
      {{- end}}
      {{- end}}
      {{- end}}
{{- end -}}
