apiVersion: v2
name: helm
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.13.0
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: 10.1.18
    condition: rabbitmq.enabled
  - name: api-admin
    repository: file://charts/api-admin
    version: 0.1.0
    condition: api-admin.enabled
  - name: service-datasource
    repository: file://charts/service-datasource
    version: 0.1.0
    condition: service-datasource.enabled
