rabbitmq:
  enabled: true
  volumePermissions:
    enabled: true
  auth:
    username: admin
    password: dev
  extraConfiguration: |-
    default_vhost = ilotusland
  service:
    type: NodePort
    nodePorts:
      amqp: 30677
      manager: 30678

redis:
  enabled: false
  auth:
    password: dev
  service:
    type: NodePort

