global: 
  replicaCount: 1
  environment: {}
  environmentRef: 
    APPLICATION_ID: metadata.name

api-admin:
  enabled: true
  image:
    repository: api-admin
    tag: latest

service-datasource:
  enabled: true
  image:
    repository: service-datasource
    tag: latest

ingress:
  enabled: true
  paths:
    - name: api-admin
      path: /api-admin/?(.*)
      servicePort: 3000
    - name: service-datasource
      path: /service-datasource/?(.*)
      servicePort: 4000
